Atareuniao
Requisitos-de-Software/2023.1-Petz pull request #20
Opened 2023-04-22 19:16 UTC by samuel-sato

| Issue |
|:-----:|
|fixes #|

# Pull Request

## 📖 Descrição
Criação da ata da reunião do dia 19/04/2023
### 🎫 Issues

## 👩‍💻 Revisor(es)
- Pedro Muniz 
- Felipe Mastromauro

2023-04-22 21:23 UTC, MastroCoder requested changes
# Correções necessárias

Corrigir erro de português ("estapas") e chamar os elementos adicionais (vídeo, tabela) no texto (Ex.: A tabela 1 descreve...).

2023-04-23 17:57 UTC, PedroFMuniz commented
> # Correções necessárias
> Corrigir erro de português ("estapas") e chamar os elementos adicionais (vídeo, tabela) no texto (Ex.: A tabela 1 descreve...).

Não há necessidade de chamada nas atas, corrigir apenas a gramática.

2023-04-23 17:57 UTC, PedroFMuniz commented on docs/atas/reuniao19042023.md
> +### Revisão estapa 1
Alterar para etapa.

2023-04-23 17:58 UTC, PedroFMuniz requested changes
Corrigir erros de português

2023-04-23 17:58 UTC, PedroFMuniz commented on docs/atas/reuniao19042023.md
> +Conforme acordado em reunião, Pedro Muniz será responsável pela criarção da persona
Alterar para "criação das personas"

2023-04-25 12:24 UTC, MastroCoder approved these changes
LGTM

2023-04-25 12:26 UTC, PedroFMuniz approved these changes
LGTM

2023-04-25 12:27 UTC, merged