Adição do Cronograma de atividades
Requisitos-de-Software/2023.1-Petz pull request #9
Opened 2023-04-15 14:59 UTC by samuel-sato

2023-04-15 16:09 UTC, PedroFMuniz requested changes
# Histórico de versão fora do padrão

Coloque o histórico de versão no final da página, inicie as versões na 1.0 e pode me colocar como revisor nele.

2023-04-15 17:18 UTC, vitormanoel17 commented
Necessário rever também atividades atribuídas ao integrante que deixou o grupo.

2023-04-16 16:09 UTC, PedroFMuniz requested changes
Colocar o histórico de versão no rodapé da página.

2023-04-16 22:07 UTC, PedroFMuniz approved these changes

2023-04-16 22:07 UTC, merged